# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e852456c1f77de64e5ce4a876965c53a7eb3b0a8015fb5d8628a778ed4ceb18953d0817eb36c5db701136f7bc49a60ec421b25b6fb2f4897ccfb0f0ee1ae2c4

test:
  secret_key_base: 59ebbc4e03684ed3bf0e6e0acb4fd76386e91744907b9974b994ddeb77b4d47725281c417ad53d31b9f1a8c1f7614cc7ad6e9da2e349c1b17d3299bad22b8ed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 						<%= ENV["SECRET_KEY_BASE"] %>
  twitch_oauth_password: 			<%= ENV["TWITCH_OAUTH_PASSWORD"] %>
  twitch_username:						<%= ENV["TWITCH_USERNAME"] %>
  childs_play_donation_page: 	<%= ENV["CHILDS_PLAY_DONATION_PAGE"] %>
  google_login: 							<%= ENV["GOOGLE_LOGIN"] %>
  google_password: 						<%= ENV["GOOGLE_PASSWORD"] %>